### PR TITLE
Add index endpoint

### PR DESCRIPTION
**Pull request by Heisjabo**
## what does this PR do?

- Add a welcome endpoint

## how this can be tested

- Clone this project

- cd in the project folder

- install all dependencies yarn

- Start the server yarn dev

- make a get request on the index route

### CODE REVIEW

**Comment by Jovz19200** [comment]
you can add a label to let us know the status

**Review by yvanddniyo — COMMENTED** [review]
you have to label your changes whether is  ready to submit or still working on it.

**Review by niyobertin — APPROVED** [review]

**Review by Jovz19200 — APPROVED** [review]

**Review by yvanddniyo — APPROVED** [review]
That's look perfect Jabo.

**Review by Habinezajanvier — APPROVED** [review]
LGTM

**Pull request merged**
